version: "3.9"

services:
  discord-bot:
    image: ghcr.io/gdsc-fsc/gdsc-bot:master
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - notification_channel=${notification_channel}